project:
  type: website
  output-dir: _site
  render:
    - about.qmd
    - index.qmd
    - posts/welcome/index.qmd

website:
  title: "About me"
  favicon: my_picture.png
  search: true
  navbar:
    left:
      - text: My CV
        file: about.qmd
      - text: Posts
        file: posts/welcome/index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: show
    smooth-scroll: true

freeze: auto